print("******************************")
print("*College: Silicon            *")
print("*Address: Silicon Hills      *")
print("*Near DLF Building           *")
print("*Patia                       *")
print("*Bhubaneswar                 *")
print("*751025                      *")
print("******************************")
